// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendasWeb.Data;

namespace VendasWeb.Migrations
{
    [DbContext(typeof(VendasWebContext))]
    [Migration("20200116144357_Teste1")]
    partial class Teste1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VendasWeb.Models.Filial", b =>
                {
                    b.Property<int>("FilialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FilialNome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FilialId");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("VendasWeb.Models.RegistroVendas", b =>
                {
                    b.Property<int>("RegistroVendasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusVenda")
                        .HasColumnType("int");

                    b.Property<float>("ValorVenda")
                        .HasColumnType("float");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("RegistroVendasId");

                    b.HasIndex("VendedorId");

                    b.ToTable("RegistroVendas");
                });

            modelBuilder.Entity("VendasWeb.Models.Vendedor", b =>
                {
                    b.Property<int>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FilialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VendedorAniversario")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VendedorEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VendedorNome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("VendedorSalario")
                        .HasColumnType("float");

                    b.HasKey("VendedorId");

                    b.HasIndex("FilialId");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("VendasWeb.Models.RegistroVendas", b =>
                {
                    b.HasOne("VendasWeb.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId");
                });

            modelBuilder.Entity("VendasWeb.Models.Vendedor", b =>
                {
                    b.HasOne("VendasWeb.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
